services:
  app:
    image: ubuntu:latest
    container_name: redrabbit_app_runner
    restart: unless-stopped
    build:
      context: .
      dockerfile: dockerfile
      args:
        USER_ID: 999
        GROUP_ID: 999
        RUNNER_NAME: REDRABBIT_APP_LOCAL_RUNNER
        URL: https://github.com/sinov8/redrabbit-flutter-app
        GITHUB_ACCESS_TOKEN: A355TUDFPVOC5S7NHCGXQK3GII77Q
        DEBIAN_FRONTEND: noninteractive
    command: ["./run.sh"]
    # volumes:
      # - D:/homelab/github_actions/:/actions-runner
      # - D:/homelab-data-1/github_action_runners/redrabbit_app:/actions-runner
    environment:
      - DEBIAN_FRONTEND=noninteractive
    user: "1000:1000"

networks:
  default:
    driver: bridge
