services:
  watchtower:
    container_name: watchtower
    restart: always
    image: containrrr/watchtower
    # ports:
    #   - 5000:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock