services:
  tautulli:
    container_name: tautulli
    restart: unless-stopped
    image: lscr.io/linuxserver/tautulli:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Johannesburg
    volumes:
      - d:/homelab/tautulli:/config
    ports:
      - 8181:8181
    dns:
      - 1.1.1.1
      - 8.8.8.8