# ./sentry_config/config.yml
system.secret-key: ${SENTRY_SECRET_KEY}

filestore.backend: filesystem
filestore.options:
  location: /data/files

symbolicator.enabled: true
symbolicator.options:
  url: http://symbolicator:3021

redis.clusters:
  default:
    hosts:
      0:
        host: redis
        port: 6379

kafka.clusters:
  default:
    bootstrap.servers: kafka:9092

snuba:
  host: snuba-api
  port: 1218
