version: '3.8'

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "8000:8000"
      - "9443:9443"
    volumes:
      - "//./pipe/docker_engine://./pipe/docker_engine"
      - "D:/14-Portainer:/data"

  portainer_agent:
    image: portainer/agent:2.19.5
    container_name: portainer_agent
    restart: always
    ports:
      - "9001:9001"
    volumes:
      - "D:/14-Portainer_Agent:/data"
      - "//./pipe/docker_engine://./pipe/docker_engine"

volumes:
  portainer_data:
