services:
  dashboard:
    container_name: dashboard
    image: 'lissy93/dashy:latest'
    volumes:
      - './dashy/my-conf.yml:/app/user-data/conf.yml'
    ports:
      - '1111:8080'
    restart: always

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: always
    ports:
      - "8000:8000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "D:/homelab/portainer:/data"


  portainer_agent:
    container_name: portainer_agent
    image: portainer/agent:2.19.5
    restart: always
    ports:
      - "9001:9001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "D:/homelab/portainer:/data"

  watchtower:
    container_name: watchtower
    restart: always
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  web:
    driver: bridge
  backend:
    external: true
