# traefik.yaml

api:
  dashboard: true
  insecure: true  # Use only in development; secure it for production.

log:
  level: DEBUG

entryPoints:
  web:
    address: ":80"
    # forwardedHeaders:
    #   - 192.168.0.110/22
    http:
      redirections:
        entryPoint:
          to: https
          scheme: http
  websecure:
    address: ":443"
    # forwardedHeaders:
    http:
      tls:
        certResolver: myResolver
      middlewares:
        - cloudflarewarp


  

http:
  middlewares:
    cloudflarewarp:
      plugin:
        cloudflarewarp:
          disableDefault: false
          trustip:
            - "2400:cb00::/32"  # Optional: Add specific IPs or ranges to trust

  routers:
    my-router:
      rule: Path(`/whoami`)
      service: service-whoami
      entryPoints:
        - websecure
      middlewares:
        - traefik-real-ip@file

  services:
    service-whoami:
      loadBalancer:
        servers:
          - url: http://127.0.0.1:5000

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false  # Only expose containers explicitly labeled.
    watch: true

accessLog:
  filePath: "/var/log/traefik/access.log"
  bufferingSize: 100  # Configuring buffering of logs.

tls:
  options:
    default:
      minVersion: VersionTLS12


certificatesResolvers:
  myresolver:
    acme:
      email: dario@neroland.co.za
      storage: /letsencrypt/acme.json
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 0

experimental:
  plugins:
    traefik-real-ip:
      moduleName: "github.com/soulbalz/traefik-real-ip"
      version: "v1.0.3"
