services:
  mysql:
    image: mysql:8.4
    container_name: shared-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"  # Optional: Only expose if you need to connect from outside Docker
    volumes:
      - D:/homelab/mysql-shared/:/var/lib/mysql
    networks:
      - shared-db-net

networks:
  shared-db-net:
    external: true
